//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XServices.NotificationCenter.NotificationCenterElements {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gsis.ggps.interoperability/notificationCenterElementsInterface", ConfigurationName="NotificationCenterElements.notificationCenterElementsInterface")]
    public interface notificationCenterElementsInterface {
        
        // CODEGEN: Generating message contract since the operation getNncIdentityExt is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getNncIdentityExt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExtResponse1 getNncIdentityExt(XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExt request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getNncIdentityExt", ReplyAction="*")]
        System.Threading.Tasks.Task<XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExtResponse1> getNncIdentityExtAsync(XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExt request);
        
        // CODEGEN: Generating message contract since the operation getNncIdentity is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getNncIdentity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        XServices.NotificationCenter.NotificationCenterElements.getNncIdentityResponse1 getNncIdentity(XServices.NotificationCenter.NotificationCenterElements.getNncIdentity request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getNncIdentity", ReplyAction="*")]
        System.Threading.Tasks.Task<XServices.NotificationCenter.NotificationCenterElements.getNncIdentityResponse1> getNncIdentityAsync(XServices.NotificationCenter.NotificationCenterElements.getNncIdentity request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/notificationCenterElementsInterface")]
    public partial class getNncIdentityExtRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditRecord auditRecordField;
        
        private getNncIdentityExtInput getNncIdentityExtInputRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auditRecord auditRecord {
            get {
                return this.auditRecordField;
            }
            set {
                this.auditRecordField = value;
                this.RaisePropertyChanged("auditRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public getNncIdentityExtInput getNncIdentityExtInputRecord {
            get {
                return this.getNncIdentityExtInputRecordField;
            }
            set {
                this.getNncIdentityExtInputRecordField = value;
                this.RaisePropertyChanged("getNncIdentityExtInputRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/notificationCenterElementsInterface")]
    public partial class auditRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string auditTransactionIdField;
        
        private System.DateTime auditTransactionDateField;
        
        private string auditUnitField;
        
        private string auditProtocolField;
        
        private string auditUserIdField;
        
        private string auditUserIpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string auditTransactionId {
            get {
                return this.auditTransactionIdField;
            }
            set {
                this.auditTransactionIdField = value;
                this.RaisePropertyChanged("auditTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime auditTransactionDate {
            get {
                return this.auditTransactionDateField;
            }
            set {
                this.auditTransactionDateField = value;
                this.RaisePropertyChanged("auditTransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string auditUnit {
            get {
                return this.auditUnitField;
            }
            set {
                this.auditUnitField = value;
                this.RaisePropertyChanged("auditUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string auditProtocol {
            get {
                return this.auditProtocolField;
            }
            set {
                this.auditProtocolField = value;
                this.RaisePropertyChanged("auditProtocol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string auditUserId {
            get {
                return this.auditUserIdField;
            }
            set {
                this.auditUserIdField = value;
                this.RaisePropertyChanged("auditUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string auditUserIp {
            get {
                return this.auditUserIpField;
            }
            set {
                this.auditUserIpField = value;
                this.RaisePropertyChanged("auditUserIp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/notificationCenterElementsInterface")]
    public partial class getNncIdentityReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryCodeField;
        
        private string countryDescrField;
        
        private string addressStreetField;
        
        private string addressNumberField;
        
        private string addressCityField;
        
        private string addressZipCodeField;
        
        private string telephoneField;
        
        private string countryCode2Field;
        
        private string countryDescr2Field;
        
        private string addressStreet2Field;
        
        private string addressNumber2Field;
        
        private string addressCity2Field;
        
        private string addressZipCode2Field;
        
        private string telephone2Field;
        
        private string mobileField;
        
        private string emailField;
        
        private string epikForeisFlagField;
        
        private string epidForeisFlagField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("countryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string countryDescr {
            get {
                return this.countryDescrField;
            }
            set {
                this.countryDescrField = value;
                this.RaisePropertyChanged("countryDescr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string addressStreet {
            get {
                return this.addressStreetField;
            }
            set {
                this.addressStreetField = value;
                this.RaisePropertyChanged("addressStreet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string addressNumber {
            get {
                return this.addressNumberField;
            }
            set {
                this.addressNumberField = value;
                this.RaisePropertyChanged("addressNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string addressCity {
            get {
                return this.addressCityField;
            }
            set {
                this.addressCityField = value;
                this.RaisePropertyChanged("addressCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string addressZipCode {
            get {
                return this.addressZipCodeField;
            }
            set {
                this.addressZipCodeField = value;
                this.RaisePropertyChanged("addressZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
                this.RaisePropertyChanged("telephone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string countryCode2 {
            get {
                return this.countryCode2Field;
            }
            set {
                this.countryCode2Field = value;
                this.RaisePropertyChanged("countryCode2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string countryDescr2 {
            get {
                return this.countryDescr2Field;
            }
            set {
                this.countryDescr2Field = value;
                this.RaisePropertyChanged("countryDescr2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string addressStreet2 {
            get {
                return this.addressStreet2Field;
            }
            set {
                this.addressStreet2Field = value;
                this.RaisePropertyChanged("addressStreet2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string addressNumber2 {
            get {
                return this.addressNumber2Field;
            }
            set {
                this.addressNumber2Field = value;
                this.RaisePropertyChanged("addressNumber2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string addressCity2 {
            get {
                return this.addressCity2Field;
            }
            set {
                this.addressCity2Field = value;
                this.RaisePropertyChanged("addressCity2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string addressZipCode2 {
            get {
                return this.addressZipCode2Field;
            }
            set {
                this.addressZipCode2Field = value;
                this.RaisePropertyChanged("addressZipCode2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string telephone2 {
            get {
                return this.telephone2Field;
            }
            set {
                this.telephone2Field = value;
                this.RaisePropertyChanged("telephone2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string epikForeisFlag {
            get {
                return this.epikForeisFlagField;
            }
            set {
                this.epikForeisFlagField = value;
                this.RaisePropertyChanged("epikForeisFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string epidForeisFlag {
            get {
                return this.epidForeisFlagField;
            }
            set {
                this.epidForeisFlagField = value;
                this.RaisePropertyChanged("epidForeisFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/notificationCenterElementsInterface")]
    public partial class getNncIdentityResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private getNncIdentityReturn getNncIdentityOutputRecordField;
        
        private decimal callSequenceIdField;
        
        private bool callSequenceIdFieldSpecified;
        
        private System.DateTime callSequenceDateField;
        
        private bool callSequenceDateFieldSpecified;
        
        private errorRecord errorRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public getNncIdentityReturn getNncIdentityOutputRecord {
            get {
                return this.getNncIdentityOutputRecordField;
            }
            set {
                this.getNncIdentityOutputRecordField = value;
                this.RaisePropertyChanged("getNncIdentityOutputRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal callSequenceId {
            get {
                return this.callSequenceIdField;
            }
            set {
                this.callSequenceIdField = value;
                this.RaisePropertyChanged("callSequenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool callSequenceIdSpecified {
            get {
                return this.callSequenceIdFieldSpecified;
            }
            set {
                this.callSequenceIdFieldSpecified = value;
                this.RaisePropertyChanged("callSequenceIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime callSequenceDate {
            get {
                return this.callSequenceDateField;
            }
            set {
                this.callSequenceDateField = value;
                this.RaisePropertyChanged("callSequenceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool callSequenceDateSpecified {
            get {
                return this.callSequenceDateFieldSpecified;
            }
            set {
                this.callSequenceDateFieldSpecified = value;
                this.RaisePropertyChanged("callSequenceDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public errorRecord errorRecord {
            get {
                return this.errorRecordField;
            }
            set {
                this.errorRecordField = value;
                this.RaisePropertyChanged("errorRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/notificationCenterElementsInterface")]
    public partial class errorRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorDescrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorDescr {
            get {
                return this.errorDescrField;
            }
            set {
                this.errorDescrField = value;
                this.RaisePropertyChanged("errorDescr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/notificationCenterElementsInterface")]
    public partial class getNncIdentityInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string afmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string afm {
            get {
                return this.afmField;
            }
            set {
                this.afmField = value;
                this.RaisePropertyChanged("afm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/notificationCenterElementsInterface")]
    public partial class getNncIdentityRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditRecord auditRecordField;
        
        private getNncIdentityInput getNncIdentityInputRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auditRecord auditRecord {
            get {
                return this.auditRecordField;
            }
            set {
                this.auditRecordField = value;
                this.RaisePropertyChanged("auditRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public getNncIdentityInput getNncIdentityInputRecord {
            get {
                return this.getNncIdentityInputRecordField;
            }
            set {
                this.getNncIdentityInputRecordField = value;
                this.RaisePropertyChanged("getNncIdentityInputRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/notificationCenterElementsInterface")]
    public partial class getNncIdentityExtReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryCodeField;
        
        private string countryDescrField;
        
        private string addressStreetField;
        
        private string addressNumberField;
        
        private string addressCityField;
        
        private string addressZipCodeField;
        
        private string regionField;
        
        private string regionalUnitField;
        
        private string municipalityField;
        
        private string municipalUnitField;
        
        private string communeField;
        
        private string localityField;
        
        private string telephoneField;
        
        private string countryCode2Field;
        
        private string countryDescr2Field;
        
        private string addressStreet2Field;
        
        private string addressNumber2Field;
        
        private string addressCity2Field;
        
        private string addressZipCode2Field;
        
        private string region2Field;
        
        private string regionalUnit2Field;
        
        private string municipality2Field;
        
        private string municipalUnit2Field;
        
        private string commune2Field;
        
        private string locality2Field;
        
        private string telephone2Field;
        
        private string mobileField;
        
        private string emailField;
        
        private string epikForeisFlagField;
        
        private string epidForeisFlagField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("countryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string countryDescr {
            get {
                return this.countryDescrField;
            }
            set {
                this.countryDescrField = value;
                this.RaisePropertyChanged("countryDescr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string addressStreet {
            get {
                return this.addressStreetField;
            }
            set {
                this.addressStreetField = value;
                this.RaisePropertyChanged("addressStreet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string addressNumber {
            get {
                return this.addressNumberField;
            }
            set {
                this.addressNumberField = value;
                this.RaisePropertyChanged("addressNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string addressCity {
            get {
                return this.addressCityField;
            }
            set {
                this.addressCityField = value;
                this.RaisePropertyChanged("addressCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string addressZipCode {
            get {
                return this.addressZipCodeField;
            }
            set {
                this.addressZipCodeField = value;
                this.RaisePropertyChanged("addressZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string regionalUnit {
            get {
                return this.regionalUnitField;
            }
            set {
                this.regionalUnitField = value;
                this.RaisePropertyChanged("regionalUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string municipality {
            get {
                return this.municipalityField;
            }
            set {
                this.municipalityField = value;
                this.RaisePropertyChanged("municipality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string municipalUnit {
            get {
                return this.municipalUnitField;
            }
            set {
                this.municipalUnitField = value;
                this.RaisePropertyChanged("municipalUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string commune {
            get {
                return this.communeField;
            }
            set {
                this.communeField = value;
                this.RaisePropertyChanged("commune");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
                this.RaisePropertyChanged("locality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
                this.RaisePropertyChanged("telephone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string countryCode2 {
            get {
                return this.countryCode2Field;
            }
            set {
                this.countryCode2Field = value;
                this.RaisePropertyChanged("countryCode2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string countryDescr2 {
            get {
                return this.countryDescr2Field;
            }
            set {
                this.countryDescr2Field = value;
                this.RaisePropertyChanged("countryDescr2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string addressStreet2 {
            get {
                return this.addressStreet2Field;
            }
            set {
                this.addressStreet2Field = value;
                this.RaisePropertyChanged("addressStreet2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string addressNumber2 {
            get {
                return this.addressNumber2Field;
            }
            set {
                this.addressNumber2Field = value;
                this.RaisePropertyChanged("addressNumber2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string addressCity2 {
            get {
                return this.addressCity2Field;
            }
            set {
                this.addressCity2Field = value;
                this.RaisePropertyChanged("addressCity2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string addressZipCode2 {
            get {
                return this.addressZipCode2Field;
            }
            set {
                this.addressZipCode2Field = value;
                this.RaisePropertyChanged("addressZipCode2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string region2 {
            get {
                return this.region2Field;
            }
            set {
                this.region2Field = value;
                this.RaisePropertyChanged("region2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string regionalUnit2 {
            get {
                return this.regionalUnit2Field;
            }
            set {
                this.regionalUnit2Field = value;
                this.RaisePropertyChanged("regionalUnit2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string municipality2 {
            get {
                return this.municipality2Field;
            }
            set {
                this.municipality2Field = value;
                this.RaisePropertyChanged("municipality2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string municipalUnit2 {
            get {
                return this.municipalUnit2Field;
            }
            set {
                this.municipalUnit2Field = value;
                this.RaisePropertyChanged("municipalUnit2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string commune2 {
            get {
                return this.commune2Field;
            }
            set {
                this.commune2Field = value;
                this.RaisePropertyChanged("commune2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string locality2 {
            get {
                return this.locality2Field;
            }
            set {
                this.locality2Field = value;
                this.RaisePropertyChanged("locality2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string telephone2 {
            get {
                return this.telephone2Field;
            }
            set {
                this.telephone2Field = value;
                this.RaisePropertyChanged("telephone2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string epikForeisFlag {
            get {
                return this.epikForeisFlagField;
            }
            set {
                this.epikForeisFlagField = value;
                this.RaisePropertyChanged("epikForeisFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string epidForeisFlag {
            get {
                return this.epidForeisFlagField;
            }
            set {
                this.epidForeisFlagField = value;
                this.RaisePropertyChanged("epidForeisFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/notificationCenterElementsInterface")]
    public partial class getNncIdentityExtResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private getNncIdentityExtReturn getNncIdentityExtOutputRecordField;
        
        private decimal callSequenceIdField;
        
        private bool callSequenceIdFieldSpecified;
        
        private System.DateTime callSequenceDateField;
        
        private bool callSequenceDateFieldSpecified;
        
        private errorRecord errorRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public getNncIdentityExtReturn getNncIdentityExtOutputRecord {
            get {
                return this.getNncIdentityExtOutputRecordField;
            }
            set {
                this.getNncIdentityExtOutputRecordField = value;
                this.RaisePropertyChanged("getNncIdentityExtOutputRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal callSequenceId {
            get {
                return this.callSequenceIdField;
            }
            set {
                this.callSequenceIdField = value;
                this.RaisePropertyChanged("callSequenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool callSequenceIdSpecified {
            get {
                return this.callSequenceIdFieldSpecified;
            }
            set {
                this.callSequenceIdFieldSpecified = value;
                this.RaisePropertyChanged("callSequenceIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime callSequenceDate {
            get {
                return this.callSequenceDateField;
            }
            set {
                this.callSequenceDateField = value;
                this.RaisePropertyChanged("callSequenceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool callSequenceDateSpecified {
            get {
                return this.callSequenceDateFieldSpecified;
            }
            set {
                this.callSequenceDateFieldSpecified = value;
                this.RaisePropertyChanged("callSequenceDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public errorRecord errorRecord {
            get {
                return this.errorRecordField;
            }
            set {
                this.errorRecordField = value;
                this.RaisePropertyChanged("errorRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/notificationCenterElementsInterface")]
    public partial class getNncIdentityExtInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string afmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string afm {
            get {
                return this.afmField;
            }
            set {
                this.afmField = value;
                this.RaisePropertyChanged("afm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNncIdentityExt {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gsis.ggps.interoperability/notificationCenterElementsInterface", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExtRequest getNncIdentityExtRequest;
        
        public getNncIdentityExt() {
        }
        
        public getNncIdentityExt(XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExtRequest getNncIdentityExtRequest) {
            this.getNncIdentityExtRequest = getNncIdentityExtRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNncIdentityExtResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gsis.ggps.interoperability/notificationCenterElementsInterface", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExtResponse getNncIdentityExtResponse;
        
        public getNncIdentityExtResponse1() {
        }
        
        public getNncIdentityExtResponse1(XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExtResponse getNncIdentityExtResponse) {
            this.getNncIdentityExtResponse = getNncIdentityExtResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNncIdentity {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gsis.ggps.interoperability/notificationCenterElementsInterface", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XServices.NotificationCenter.NotificationCenterElements.getNncIdentityRequest getNncIdentityRequest;
        
        public getNncIdentity() {
        }
        
        public getNncIdentity(XServices.NotificationCenter.NotificationCenterElements.getNncIdentityRequest getNncIdentityRequest) {
            this.getNncIdentityRequest = getNncIdentityRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNncIdentityResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gsis.ggps.interoperability/notificationCenterElementsInterface", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XServices.NotificationCenter.NotificationCenterElements.getNncIdentityResponse getNncIdentityResponse;
        
        public getNncIdentityResponse1() {
        }
        
        public getNncIdentityResponse1(XServices.NotificationCenter.NotificationCenterElements.getNncIdentityResponse getNncIdentityResponse) {
            this.getNncIdentityResponse = getNncIdentityResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface notificationCenterElementsInterfaceChannel : XServices.NotificationCenter.NotificationCenterElements.notificationCenterElementsInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class notificationCenterElementsInterfaceClient : System.ServiceModel.ClientBase<XServices.NotificationCenter.NotificationCenterElements.notificationCenterElementsInterface>, XServices.NotificationCenter.NotificationCenterElements.notificationCenterElementsInterface {
        
        public notificationCenterElementsInterfaceClient() {
        }
        
        public notificationCenterElementsInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public notificationCenterElementsInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public notificationCenterElementsInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public notificationCenterElementsInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExtResponse1 XServices.NotificationCenter.NotificationCenterElements.notificationCenterElementsInterface.getNncIdentityExt(XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExt request) {
            return base.Channel.getNncIdentityExt(request);
        }
        
        public XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExtResponse getNncIdentityExt(XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExtRequest getNncIdentityExtRequest) {
            XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExt inValue = new XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExt();
            inValue.getNncIdentityExtRequest = getNncIdentityExtRequest;
            XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExtResponse1 retVal = ((XServices.NotificationCenter.NotificationCenterElements.notificationCenterElementsInterface)(this)).getNncIdentityExt(inValue);
            return retVal.getNncIdentityExtResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExtResponse1> XServices.NotificationCenter.NotificationCenterElements.notificationCenterElementsInterface.getNncIdentityExtAsync(XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExt request) {
            return base.Channel.getNncIdentityExtAsync(request);
        }
        
        public System.Threading.Tasks.Task<XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExtResponse1> getNncIdentityExtAsync(XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExtRequest getNncIdentityExtRequest) {
            XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExt inValue = new XServices.NotificationCenter.NotificationCenterElements.getNncIdentityExt();
            inValue.getNncIdentityExtRequest = getNncIdentityExtRequest;
            return ((XServices.NotificationCenter.NotificationCenterElements.notificationCenterElementsInterface)(this)).getNncIdentityExtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XServices.NotificationCenter.NotificationCenterElements.getNncIdentityResponse1 XServices.NotificationCenter.NotificationCenterElements.notificationCenterElementsInterface.getNncIdentity(XServices.NotificationCenter.NotificationCenterElements.getNncIdentity request) {
            return base.Channel.getNncIdentity(request);
        }
        
        public XServices.NotificationCenter.NotificationCenterElements.getNncIdentityResponse getNncIdentity(XServices.NotificationCenter.NotificationCenterElements.getNncIdentityRequest getNncIdentityRequest) {
            XServices.NotificationCenter.NotificationCenterElements.getNncIdentity inValue = new XServices.NotificationCenter.NotificationCenterElements.getNncIdentity();
            inValue.getNncIdentityRequest = getNncIdentityRequest;
            XServices.NotificationCenter.NotificationCenterElements.getNncIdentityResponse1 retVal = ((XServices.NotificationCenter.NotificationCenterElements.notificationCenterElementsInterface)(this)).getNncIdentity(inValue);
            return retVal.getNncIdentityResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XServices.NotificationCenter.NotificationCenterElements.getNncIdentityResponse1> XServices.NotificationCenter.NotificationCenterElements.notificationCenterElementsInterface.getNncIdentityAsync(XServices.NotificationCenter.NotificationCenterElements.getNncIdentity request) {
            return base.Channel.getNncIdentityAsync(request);
        }
        
        public System.Threading.Tasks.Task<XServices.NotificationCenter.NotificationCenterElements.getNncIdentityResponse1> getNncIdentityAsync(XServices.NotificationCenter.NotificationCenterElements.getNncIdentityRequest getNncIdentityRequest) {
            XServices.NotificationCenter.NotificationCenterElements.getNncIdentity inValue = new XServices.NotificationCenter.NotificationCenterElements.getNncIdentity();
            inValue.getNncIdentityRequest = getNncIdentityRequest;
            return ((XServices.NotificationCenter.NotificationCenterElements.notificationCenterElementsInterface)(this)).getNncIdentityAsync(inValue);
        }
    }
}
