//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XServices.Idika.Service.AK_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class DataResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AFM_MELWNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KEP_ID_DIEKPERAIWSHSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KWD_NOMOY_DIEYQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KWD_NOMOY_DIEYQ_ALLHLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MELHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MESSAGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RESULTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TAXYKWDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TAXYKWD_ALLHLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AFM_MELWN {
            get {
                return this.AFM_MELWNField;
            }
            set {
                if ((object.ReferenceEquals(this.AFM_MELWNField, value) != true)) {
                    this.AFM_MELWNField = value;
                    this.RaisePropertyChanged("AFM_MELWN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KEP_ID_DIEKPERAIWSHS {
            get {
                return this.KEP_ID_DIEKPERAIWSHSField;
            }
            set {
                if ((object.ReferenceEquals(this.KEP_ID_DIEKPERAIWSHSField, value) != true)) {
                    this.KEP_ID_DIEKPERAIWSHSField = value;
                    this.RaisePropertyChanged("KEP_ID_DIEKPERAIWSHS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KWD_NOMOY_DIEYQ {
            get {
                return this.KWD_NOMOY_DIEYQField;
            }
            set {
                if ((object.ReferenceEquals(this.KWD_NOMOY_DIEYQField, value) != true)) {
                    this.KWD_NOMOY_DIEYQField = value;
                    this.RaisePropertyChanged("KWD_NOMOY_DIEYQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KWD_NOMOY_DIEYQ_ALLHL {
            get {
                return this.KWD_NOMOY_DIEYQ_ALLHLField;
            }
            set {
                if ((object.ReferenceEquals(this.KWD_NOMOY_DIEYQ_ALLHLField, value) != true)) {
                    this.KWD_NOMOY_DIEYQ_ALLHLField = value;
                    this.RaisePropertyChanged("KWD_NOMOY_DIEYQ_ALLHL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MELH {
            get {
                return this.MELHField;
            }
            set {
                if ((this.MELHField.Equals(value) != true)) {
                    this.MELHField = value;
                    this.RaisePropertyChanged("MELH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MESSAGE {
            get {
                return this.MESSAGEField;
            }
            set {
                if ((object.ReferenceEquals(this.MESSAGEField, value) != true)) {
                    this.MESSAGEField = value;
                    this.RaisePropertyChanged("MESSAGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RESULT {
            get {
                return this.RESULTField;
            }
            set {
                if ((this.RESULTField.Equals(value) != true)) {
                    this.RESULTField = value;
                    this.RaisePropertyChanged("RESULT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TAXYKWD {
            get {
                return this.TAXYKWDField;
            }
            set {
                if ((object.ReferenceEquals(this.TAXYKWDField, value) != true)) {
                    this.TAXYKWDField = value;
                    this.RaisePropertyChanged("TAXYKWD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TAXYKWD_ALLHL {
            get {
                return this.TAXYKWD_ALLHLField;
            }
            set {
                if ((object.ReferenceEquals(this.TAXYKWD_ALLHLField, value) != true)) {
                    this.TAXYKWD_ALLHLField = value;
                    this.RaisePropertyChanged("TAXYKWD_ALLHL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AK_ServiceReference.IAK_Check")]
    public interface IAK_Check {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAK_Check/ElegxosEntaxhs", ReplyAction="http://tempuri.org/IAK_Check/ElegxosEntaxhsResponse")]
        XServices.Idika.Service.AK_ServiceReference.DataResponse ElegxosEntaxhs(string username, string password, string AMKA, string AFM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAK_Check/ElegxosEntaxhs", ReplyAction="http://tempuri.org/IAK_Check/ElegxosEntaxhsResponse")]
        System.Threading.Tasks.Task<XServices.Idika.Service.AK_ServiceReference.DataResponse> ElegxosEntaxhsAsync(string username, string password, string AMKA, string AFM);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAK_CheckChannel : XServices.Idika.Service.AK_ServiceReference.IAK_Check, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AK_CheckClient : System.ServiceModel.ClientBase<XServices.Idika.Service.AK_ServiceReference.IAK_Check>, XServices.Idika.Service.AK_ServiceReference.IAK_Check {
        
        public AK_CheckClient() {
        }
        
        public AK_CheckClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AK_CheckClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AK_CheckClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AK_CheckClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public XServices.Idika.Service.AK_ServiceReference.DataResponse ElegxosEntaxhs(string username, string password, string AMKA, string AFM) {
            return base.Channel.ElegxosEntaxhs(username, password, AMKA, AFM);
        }
        
        public System.Threading.Tasks.Task<XServices.Idika.Service.AK_ServiceReference.DataResponse> ElegxosEntaxhsAsync(string username, string password, string AMKA, string AFM) {
            return base.Channel.ElegxosEntaxhsAsync(username, password, AMKA, AFM);
        }
    }
}
