//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XServices.Edto.PolicePersonalDetailsEDTOService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gsis.ggps.interoperability/policePersonalDetailsEDTOInterface", ConfigurationName="PolicePersonalDetailsEDTOService.policePersonalDetailsEDTOInterface")]
    public interface policePersonalDetailsEDTOInterface {
        
        // CODEGEN: Generating message contract since the operation getPersonDetailsEDTO is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getPersonDetailsEDTO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTOResponse1 getPersonDetailsEDTO(XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTO request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getPersonDetailsEDTO", ReplyAction="*")]
        System.Threading.Tasks.Task<XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTOResponse1> getPersonDetailsEDTOAsync(XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTO request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/policePersonalDetailsEDTOInterface")]
    public partial class getPersonDetailsEDTORequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditRecord auditRecordField;
        
        private getPersonDetailsEDTOInput getPersonDetailsEDTOInputRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auditRecord auditRecord {
            get {
                return this.auditRecordField;
            }
            set {
                this.auditRecordField = value;
                this.RaisePropertyChanged("auditRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public getPersonDetailsEDTOInput getPersonDetailsEDTOInputRecord {
            get {
                return this.getPersonDetailsEDTOInputRecordField;
            }
            set {
                this.getPersonDetailsEDTOInputRecordField = value;
                this.RaisePropertyChanged("getPersonDetailsEDTOInputRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/policePersonalDetailsEDTOInterface")]
    public partial class auditRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string auditTransactionIdField;
        
        private System.DateTime auditTransactionDateField;
        
        private string auditUnitField;
        
        private string auditProtocolField;
        
        private string auditUserIdField;
        
        private string auditUserIpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string auditTransactionId {
            get {
                return this.auditTransactionIdField;
            }
            set {
                this.auditTransactionIdField = value;
                this.RaisePropertyChanged("auditTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime auditTransactionDate {
            get {
                return this.auditTransactionDateField;
            }
            set {
                this.auditTransactionDateField = value;
                this.RaisePropertyChanged("auditTransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string auditUnit {
            get {
                return this.auditUnitField;
            }
            set {
                this.auditUnitField = value;
                this.RaisePropertyChanged("auditUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string auditProtocol {
            get {
                return this.auditProtocolField;
            }
            set {
                this.auditProtocolField = value;
                this.RaisePropertyChanged("auditProtocol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string auditUserId {
            get {
                return this.auditUserIdField;
            }
            set {
                this.auditUserIdField = value;
                this.RaisePropertyChanged("auditUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string auditUserIp {
            get {
                return this.auditUserIpField;
            }
            set {
                this.auditUserIpField = value;
                this.RaisePropertyChanged("auditUserIp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/policePersonalDetailsEDTOInterface")]
    public partial class errorRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorDescrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorDescr {
            get {
                return this.errorDescrField;
            }
            set {
                this.errorDescrField = value;
                this.RaisePropertyChanged("errorDescr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/policePersonalDetailsEDTOInterface")]
    public partial class efkaPermitCaseRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string permitTypeField;
        
        private string permitReasonField;
        
        private string protocolIdField;
        
        private string protocolDateField;
        
        private string permitStatusField;
        
        private string officeBookIdField;
        
        private string officeFolderField;
        
        private string permitNumberField;
        
        private string effectiveDateField;
        
        private string expiryDateField;
        
        private string administrationDateField;
        
        private string formerResidenceCountryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string permitType {
            get {
                return this.permitTypeField;
            }
            set {
                this.permitTypeField = value;
                this.RaisePropertyChanged("permitType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string permitReason {
            get {
                return this.permitReasonField;
            }
            set {
                this.permitReasonField = value;
                this.RaisePropertyChanged("permitReason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string protocolId {
            get {
                return this.protocolIdField;
            }
            set {
                this.protocolIdField = value;
                this.RaisePropertyChanged("protocolId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string protocolDate {
            get {
                return this.protocolDateField;
            }
            set {
                this.protocolDateField = value;
                this.RaisePropertyChanged("protocolDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string permitStatus {
            get {
                return this.permitStatusField;
            }
            set {
                this.permitStatusField = value;
                this.RaisePropertyChanged("permitStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string officeBookId {
            get {
                return this.officeBookIdField;
            }
            set {
                this.officeBookIdField = value;
                this.RaisePropertyChanged("officeBookId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string officeFolder {
            get {
                return this.officeFolderField;
            }
            set {
                this.officeFolderField = value;
                this.RaisePropertyChanged("officeFolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string permitNumber {
            get {
                return this.permitNumberField;
            }
            set {
                this.permitNumberField = value;
                this.RaisePropertyChanged("permitNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string effectiveDate {
            get {
                return this.effectiveDateField;
            }
            set {
                this.effectiveDateField = value;
                this.RaisePropertyChanged("effectiveDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
                this.RaisePropertyChanged("expiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string administrationDate {
            get {
                return this.administrationDateField;
            }
            set {
                this.administrationDateField = value;
                this.RaisePropertyChanged("administrationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string formerResidenceCountry {
            get {
                return this.formerResidenceCountryField;
            }
            set {
                this.formerResidenceCountryField = value;
                this.RaisePropertyChanged("formerResidenceCountry");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/policePersonalDetailsEDTOInterface")]
    public partial class returnRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string folderNumberField;
        
        private string morfhField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string fathersNameField;
        
        private string mothersNameField;
        
        private string birthDateField;
        
        private string birthPlaceField;
        
        private string genderField;
        
        private string[] citizenshipsField;
        
        private string occupationField;
        
        private string nationalityField;
        
        private string maritalStatusField;
        
        private string phoneNumberField;
        
        private string emailField;
        
        private string homeAddressField;
        
        private string additionalResidenceDataField;
        
        private string workAddressField;
        
        private string additionalWorkDataField;
        
        private string typeField;
        
        private efkaPermitCaseRecord[] efkaPermitCaseDTOSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string folderNumber {
            get {
                return this.folderNumberField;
            }
            set {
                this.folderNumberField = value;
                this.RaisePropertyChanged("folderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string morfh {
            get {
                return this.morfhField;
            }
            set {
                this.morfhField = value;
                this.RaisePropertyChanged("morfh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fathersName {
            get {
                return this.fathersNameField;
            }
            set {
                this.fathersNameField = value;
                this.RaisePropertyChanged("fathersName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string mothersName {
            get {
                return this.mothersNameField;
            }
            set {
                this.mothersNameField = value;
                this.RaisePropertyChanged("mothersName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("birthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string birthPlace {
            get {
                return this.birthPlaceField;
            }
            set {
                this.birthPlaceField = value;
                this.RaisePropertyChanged("birthPlace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] citizenships {
            get {
                return this.citizenshipsField;
            }
            set {
                this.citizenshipsField = value;
                this.RaisePropertyChanged("citizenships");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string occupation {
            get {
                return this.occupationField;
            }
            set {
                this.occupationField = value;
                this.RaisePropertyChanged("occupation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
                this.RaisePropertyChanged("nationality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string maritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
                this.RaisePropertyChanged("maritalStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("phoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string homeAddress {
            get {
                return this.homeAddressField;
            }
            set {
                this.homeAddressField = value;
                this.RaisePropertyChanged("homeAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string additionalResidenceData {
            get {
                return this.additionalResidenceDataField;
            }
            set {
                this.additionalResidenceDataField = value;
                this.RaisePropertyChanged("additionalResidenceData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string workAddress {
            get {
                return this.workAddressField;
            }
            set {
                this.workAddressField = value;
                this.RaisePropertyChanged("workAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string additionalWorkData {
            get {
                return this.additionalWorkDataField;
            }
            set {
                this.additionalWorkDataField = value;
                this.RaisePropertyChanged("additionalWorkData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public efkaPermitCaseRecord[] efkaPermitCaseDTOS {
            get {
                return this.efkaPermitCaseDTOSField;
            }
            set {
                this.efkaPermitCaseDTOSField = value;
                this.RaisePropertyChanged("efkaPermitCaseDTOS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/policePersonalDetailsEDTOInterface")]
    public partial class getPersonDetailsEDTOReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private returnRecord[] returnsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public returnRecord[] returns {
            get {
                return this.returnsField;
            }
            set {
                this.returnsField = value;
                this.RaisePropertyChanged("returns");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/policePersonalDetailsEDTOInterface")]
    public partial class getPersonDetailsEDTOResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private getPersonDetailsEDTOReturn getPersonDetailsEDTOOutputRecordField;
        
        private decimal callSequenceIdField;
        
        private bool callSequenceIdFieldSpecified;
        
        private System.DateTime callSequenceDateField;
        
        private bool callSequenceDateFieldSpecified;
        
        private errorRecord errorRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public getPersonDetailsEDTOReturn getPersonDetailsEDTOOutputRecord {
            get {
                return this.getPersonDetailsEDTOOutputRecordField;
            }
            set {
                this.getPersonDetailsEDTOOutputRecordField = value;
                this.RaisePropertyChanged("getPersonDetailsEDTOOutputRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal callSequenceId {
            get {
                return this.callSequenceIdField;
            }
            set {
                this.callSequenceIdField = value;
                this.RaisePropertyChanged("callSequenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool callSequenceIdSpecified {
            get {
                return this.callSequenceIdFieldSpecified;
            }
            set {
                this.callSequenceIdFieldSpecified = value;
                this.RaisePropertyChanged("callSequenceIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime callSequenceDate {
            get {
                return this.callSequenceDateField;
            }
            set {
                this.callSequenceDateField = value;
                this.RaisePropertyChanged("callSequenceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool callSequenceDateSpecified {
            get {
                return this.callSequenceDateFieldSpecified;
            }
            set {
                this.callSequenceDateFieldSpecified = value;
                this.RaisePropertyChanged("callSequenceDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public errorRecord errorRecord {
            get {
                return this.errorRecordField;
            }
            set {
                this.errorRecordField = value;
                this.RaisePropertyChanged("errorRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/policePersonalDetailsEDTOInterface")]
    public partial class getPersonDetailsEDTOInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string permitNumberField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string fathersNameField;
        
        private string mothersNameField;
        
        private string birthDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string permitNumber {
            get {
                return this.permitNumberField;
            }
            set {
                this.permitNumberField = value;
                this.RaisePropertyChanged("permitNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fathersName {
            get {
                return this.fathersNameField;
            }
            set {
                this.fathersNameField = value;
                this.RaisePropertyChanged("fathersName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string mothersName {
            get {
                return this.mothersNameField;
            }
            set {
                this.mothersNameField = value;
                this.RaisePropertyChanged("mothersName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("birthDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPersonDetailsEDTO {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gsis.ggps.interoperability/policePersonalDetailsEDTOInterface", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTORequest getPersonDetailsEDTORequest;
        
        public getPersonDetailsEDTO() {
        }
        
        public getPersonDetailsEDTO(XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTORequest getPersonDetailsEDTORequest) {
            this.getPersonDetailsEDTORequest = getPersonDetailsEDTORequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPersonDetailsEDTOResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gsis.ggps.interoperability/policePersonalDetailsEDTOInterface", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTOResponse getPersonDetailsEDTOResponse;
        
        public getPersonDetailsEDTOResponse1() {
        }
        
        public getPersonDetailsEDTOResponse1(XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTOResponse getPersonDetailsEDTOResponse) {
            this.getPersonDetailsEDTOResponse = getPersonDetailsEDTOResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface policePersonalDetailsEDTOInterfaceChannel : XServices.Edto.PolicePersonalDetailsEDTOService.policePersonalDetailsEDTOInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class policePersonalDetailsEDTOInterfaceClient : System.ServiceModel.ClientBase<XServices.Edto.PolicePersonalDetailsEDTOService.policePersonalDetailsEDTOInterface>, XServices.Edto.PolicePersonalDetailsEDTOService.policePersonalDetailsEDTOInterface {
        
        public policePersonalDetailsEDTOInterfaceClient() {
        }
        
        public policePersonalDetailsEDTOInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public policePersonalDetailsEDTOInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public policePersonalDetailsEDTOInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public policePersonalDetailsEDTOInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTOResponse1 XServices.Edto.PolicePersonalDetailsEDTOService.policePersonalDetailsEDTOInterface.getPersonDetailsEDTO(XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTO request) {
            return base.Channel.getPersonDetailsEDTO(request);
        }
        
        public XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTOResponse getPersonDetailsEDTO(XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTORequest getPersonDetailsEDTORequest) {
            XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTO inValue = new XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTO();
            inValue.getPersonDetailsEDTORequest = getPersonDetailsEDTORequest;
            XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTOResponse1 retVal = ((XServices.Edto.PolicePersonalDetailsEDTOService.policePersonalDetailsEDTOInterface)(this)).getPersonDetailsEDTO(inValue);
            return retVal.getPersonDetailsEDTOResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTOResponse1> XServices.Edto.PolicePersonalDetailsEDTOService.policePersonalDetailsEDTOInterface.getPersonDetailsEDTOAsync(XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTO request) {
            return base.Channel.getPersonDetailsEDTOAsync(request);
        }
        
        public System.Threading.Tasks.Task<XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTOResponse1> getPersonDetailsEDTOAsync(XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTORequest getPersonDetailsEDTORequest) {
            XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTO inValue = new XServices.Edto.PolicePersonalDetailsEDTOService.getPersonDetailsEDTO();
            inValue.getPersonDetailsEDTORequest = getPersonDetailsEDTORequest;
            return ((XServices.Edto.PolicePersonalDetailsEDTOService.policePersonalDetailsEDTOInterface)(this)).getPersonDetailsEDTOAsync(inValue);
        }
    }
}
