//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XServices.Efka.SalaryEmpInfoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface", ConfigurationName="SalaryEmpInfoServiceReference.salaryEmpInfoInterface")]
    public interface salaryEmpInfoInterface {
        
        // CODEGEN: Generating message contract since the operation getSalaryEmpInfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getSalaryEmpInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfoResponse1 getSalaryEmpInfo(XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getSalaryEmpInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfoResponse1> getSalaryEmpInfoAsync(XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfo request);
        
        // CODEGEN: Generating message contract since the operation requestPensionsOpeka is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="requestPensionsOpeka", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpekaResponse1 requestPensionsOpeka(XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpeka request);
        
        [System.ServiceModel.OperationContractAttribute(Action="requestPensionsOpeka", ReplyAction="*")]
        System.Threading.Tasks.Task<XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpekaResponse1> requestPensionsOpekaAsync(XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpeka request);
        
        // CODEGEN: Generating message contract since the operation getSalaryPensEmpInfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getSalaryPensEmpInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfoResponse1 getSalaryPensEmpInfo(XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getSalaryPensEmpInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfoResponse1> getSalaryPensEmpInfoAsync(XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfo request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface")]
    public partial class getSalaryEmpInfoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditRecord auditRecordField;
        
        private getSalaryEmpInfoInput getSalaryEmpInfoInputRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auditRecord auditRecord {
            get {
                return this.auditRecordField;
            }
            set {
                this.auditRecordField = value;
                this.RaisePropertyChanged("auditRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public getSalaryEmpInfoInput getSalaryEmpInfoInputRecord {
            get {
                return this.getSalaryEmpInfoInputRecordField;
            }
            set {
                this.getSalaryEmpInfoInputRecordField = value;
                this.RaisePropertyChanged("getSalaryEmpInfoInputRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface")]
    public partial class auditRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string auditTransactionIdField;
        
        private System.DateTime auditTransactionDateField;
        
        private string auditUnitField;
        
        private string auditProtocolField;
        
        private string auditUserIdField;
        
        private string auditUserIpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string auditTransactionId {
            get {
                return this.auditTransactionIdField;
            }
            set {
                this.auditTransactionIdField = value;
                this.RaisePropertyChanged("auditTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime auditTransactionDate {
            get {
                return this.auditTransactionDateField;
            }
            set {
                this.auditTransactionDateField = value;
                this.RaisePropertyChanged("auditTransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string auditUnit {
            get {
                return this.auditUnitField;
            }
            set {
                this.auditUnitField = value;
                this.RaisePropertyChanged("auditUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string auditProtocol {
            get {
                return this.auditProtocolField;
            }
            set {
                this.auditProtocolField = value;
                this.RaisePropertyChanged("auditProtocol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string auditUserId {
            get {
                return this.auditUserIdField;
            }
            set {
                this.auditUserIdField = value;
                this.RaisePropertyChanged("auditUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string auditUserIp {
            get {
                return this.auditUserIpField;
            }
            set {
                this.auditUserIpField = value;
                this.RaisePropertyChanged("auditUserIp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface")]
    public partial class pensionRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fMonthField;
        
        private string fSalaryField;
        
        private string fYearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fMonth {
            get {
                return this.fMonthField;
            }
            set {
                this.fMonthField = value;
                this.RaisePropertyChanged("fMonth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fSalary {
            get {
                return this.fSalaryField;
            }
            set {
                this.fSalaryField = value;
                this.RaisePropertyChanged("fSalary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fYear {
            get {
                return this.fYearField;
            }
            set {
                this.fYearField = value;
                this.RaisePropertyChanged("fYear");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface")]
    public partial class getSalaryPensEmpInfoReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string afmCheckField;
        
        private string amkaAfmCheckField;
        
        private string amkaCheckField;
        
        private pensionRecord[] pensionsField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string afmCheck {
            get {
                return this.afmCheckField;
            }
            set {
                this.afmCheckField = value;
                this.RaisePropertyChanged("afmCheck");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string amkaAfmCheck {
            get {
                return this.amkaAfmCheckField;
            }
            set {
                this.amkaAfmCheckField = value;
                this.RaisePropertyChanged("amkaAfmCheck");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string amkaCheck {
            get {
                return this.amkaCheckField;
            }
            set {
                this.amkaCheckField = value;
                this.RaisePropertyChanged("amkaCheck");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public pensionRecord[] pensions {
            get {
                return this.pensionsField;
            }
            set {
                this.pensionsField = value;
                this.RaisePropertyChanged("pensions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
                this.RaisePropertyChanged("successSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface")]
    public partial class getSalaryPensEmpInfoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private getSalaryPensEmpInfoReturn getSalaryPensEmpInfoOutputRecordField;
        
        private decimal callSequenceIdField;
        
        private bool callSequenceIdFieldSpecified;
        
        private System.DateTime callSequenceDateField;
        
        private bool callSequenceDateFieldSpecified;
        
        private errorRecord errorRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public getSalaryPensEmpInfoReturn getSalaryPensEmpInfoOutputRecord {
            get {
                return this.getSalaryPensEmpInfoOutputRecordField;
            }
            set {
                this.getSalaryPensEmpInfoOutputRecordField = value;
                this.RaisePropertyChanged("getSalaryPensEmpInfoOutputRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal callSequenceId {
            get {
                return this.callSequenceIdField;
            }
            set {
                this.callSequenceIdField = value;
                this.RaisePropertyChanged("callSequenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool callSequenceIdSpecified {
            get {
                return this.callSequenceIdFieldSpecified;
            }
            set {
                this.callSequenceIdFieldSpecified = value;
                this.RaisePropertyChanged("callSequenceIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime callSequenceDate {
            get {
                return this.callSequenceDateField;
            }
            set {
                this.callSequenceDateField = value;
                this.RaisePropertyChanged("callSequenceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool callSequenceDateSpecified {
            get {
                return this.callSequenceDateFieldSpecified;
            }
            set {
                this.callSequenceDateFieldSpecified = value;
                this.RaisePropertyChanged("callSequenceDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public errorRecord errorRecord {
            get {
                return this.errorRecordField;
            }
            set {
                this.errorRecordField = value;
                this.RaisePropertyChanged("errorRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface")]
    public partial class errorRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorDescrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorDescr {
            get {
                return this.errorDescrField;
            }
            set {
                this.errorDescrField = value;
                this.RaisePropertyChanged("errorDescr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface")]
    public partial class getSalaryPensEmpInfoInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string amkaField;
        
        private string afmField;
        
        private decimal monthFromField;
        
        private bool monthFromFieldSpecified;
        
        private decimal yearFromField;
        
        private bool yearFromFieldSpecified;
        
        private decimal monthToField;
        
        private bool monthToFieldSpecified;
        
        private decimal yearToField;
        
        private bool yearToFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string amka {
            get {
                return this.amkaField;
            }
            set {
                this.amkaField = value;
                this.RaisePropertyChanged("amka");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string afm {
            get {
                return this.afmField;
            }
            set {
                this.afmField = value;
                this.RaisePropertyChanged("afm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal monthFrom {
            get {
                return this.monthFromField;
            }
            set {
                this.monthFromField = value;
                this.RaisePropertyChanged("monthFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool monthFromSpecified {
            get {
                return this.monthFromFieldSpecified;
            }
            set {
                this.monthFromFieldSpecified = value;
                this.RaisePropertyChanged("monthFromSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal yearFrom {
            get {
                return this.yearFromField;
            }
            set {
                this.yearFromField = value;
                this.RaisePropertyChanged("yearFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearFromSpecified {
            get {
                return this.yearFromFieldSpecified;
            }
            set {
                this.yearFromFieldSpecified = value;
                this.RaisePropertyChanged("yearFromSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal monthTo {
            get {
                return this.monthToField;
            }
            set {
                this.monthToField = value;
                this.RaisePropertyChanged("monthTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool monthToSpecified {
            get {
                return this.monthToFieldSpecified;
            }
            set {
                this.monthToFieldSpecified = value;
                this.RaisePropertyChanged("monthToSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal yearTo {
            get {
                return this.yearToField;
            }
            set {
                this.yearToField = value;
                this.RaisePropertyChanged("yearTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearToSpecified {
            get {
                return this.yearToFieldSpecified;
            }
            set {
                this.yearToFieldSpecified = value;
                this.RaisePropertyChanged("yearToSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface")]
    public partial class getSalaryPensEmpInfoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditRecord auditRecordField;
        
        private getSalaryPensEmpInfoInput getSalaryPensEmpInfoInputRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auditRecord auditRecord {
            get {
                return this.auditRecordField;
            }
            set {
                this.auditRecordField = value;
                this.RaisePropertyChanged("auditRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public getSalaryPensEmpInfoInput getSalaryPensEmpInfoInputRecord {
            get {
                return this.getSalaryPensEmpInfoInputRecordField;
            }
            set {
                this.getSalaryPensEmpInfoInputRecordField = value;
                this.RaisePropertyChanged("getSalaryPensEmpInfoInputRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface")]
    public partial class pensionOpekaRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private string createdByField;
        
        private System.DateTime creationDateField;
        
        private bool creationDateFieldSpecified;
        
        private string amkaIdField;
        
        private string taxationIdField;
        
        private string nameField;
        
        private string surnameField;
        
        private string fatherNameField;
        
        private decimal monthField;
        
        private bool monthFieldSpecified;
        
        private decimal yearField;
        
        private bool yearFieldSpecified;
        
        private decimal grossAmntBasicField;
        
        private bool grossAmntBasicFieldSpecified;
        
        private decimal grossAmntEpikField;
        
        private bool grossAmntEpikFieldSpecified;
        
        private decimal sidField;
        
        private bool sidFieldSpecified;
        
        private decimal statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
                this.RaisePropertyChanged("successSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string createdBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("createdBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime creationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("creationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationDateSpecified {
            get {
                return this.creationDateFieldSpecified;
            }
            set {
                this.creationDateFieldSpecified = value;
                this.RaisePropertyChanged("creationDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string amkaId {
            get {
                return this.amkaIdField;
            }
            set {
                this.amkaIdField = value;
                this.RaisePropertyChanged("amkaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string taxationId {
            get {
                return this.taxationIdField;
            }
            set {
                this.taxationIdField = value;
                this.RaisePropertyChanged("taxationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string fatherName {
            get {
                return this.fatherNameField;
            }
            set {
                this.fatherNameField = value;
                this.RaisePropertyChanged("fatherName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
                this.RaisePropertyChanged("month");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool monthSpecified {
            get {
                return this.monthFieldSpecified;
            }
            set {
                this.monthFieldSpecified = value;
                this.RaisePropertyChanged("monthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearSpecified {
            get {
                return this.yearFieldSpecified;
            }
            set {
                this.yearFieldSpecified = value;
                this.RaisePropertyChanged("yearSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal grossAmntBasic {
            get {
                return this.grossAmntBasicField;
            }
            set {
                this.grossAmntBasicField = value;
                this.RaisePropertyChanged("grossAmntBasic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grossAmntBasicSpecified {
            get {
                return this.grossAmntBasicFieldSpecified;
            }
            set {
                this.grossAmntBasicFieldSpecified = value;
                this.RaisePropertyChanged("grossAmntBasicSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal grossAmntEpik {
            get {
                return this.grossAmntEpikField;
            }
            set {
                this.grossAmntEpikField = value;
                this.RaisePropertyChanged("grossAmntEpik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grossAmntEpikSpecified {
            get {
                return this.grossAmntEpikFieldSpecified;
            }
            set {
                this.grossAmntEpikFieldSpecified = value;
                this.RaisePropertyChanged("grossAmntEpikSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal sid {
            get {
                return this.sidField;
            }
            set {
                this.sidField = value;
                this.RaisePropertyChanged("sid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sidSpecified {
            get {
                return this.sidFieldSpecified;
            }
            set {
                this.sidFieldSpecified = value;
                this.RaisePropertyChanged("sidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public decimal status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface")]
    public partial class requestPensionsOpekaReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private pensionOpekaRecord[] pensionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public pensionOpekaRecord[] pensions {
            get {
                return this.pensionsField;
            }
            set {
                this.pensionsField = value;
                this.RaisePropertyChanged("pensions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface")]
    public partial class requestPensionsOpekaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private requestPensionsOpekaReturn requestPensionsOpekaOutputRecordField;
        
        private decimal callSequenceIdField;
        
        private bool callSequenceIdFieldSpecified;
        
        private System.DateTime callSequenceDateField;
        
        private bool callSequenceDateFieldSpecified;
        
        private errorRecord errorRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public requestPensionsOpekaReturn requestPensionsOpekaOutputRecord {
            get {
                return this.requestPensionsOpekaOutputRecordField;
            }
            set {
                this.requestPensionsOpekaOutputRecordField = value;
                this.RaisePropertyChanged("requestPensionsOpekaOutputRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal callSequenceId {
            get {
                return this.callSequenceIdField;
            }
            set {
                this.callSequenceIdField = value;
                this.RaisePropertyChanged("callSequenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool callSequenceIdSpecified {
            get {
                return this.callSequenceIdFieldSpecified;
            }
            set {
                this.callSequenceIdFieldSpecified = value;
                this.RaisePropertyChanged("callSequenceIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime callSequenceDate {
            get {
                return this.callSequenceDateField;
            }
            set {
                this.callSequenceDateField = value;
                this.RaisePropertyChanged("callSequenceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool callSequenceDateSpecified {
            get {
                return this.callSequenceDateFieldSpecified;
            }
            set {
                this.callSequenceDateFieldSpecified = value;
                this.RaisePropertyChanged("callSequenceDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public errorRecord errorRecord {
            get {
                return this.errorRecordField;
            }
            set {
                this.errorRecordField = value;
                this.RaisePropertyChanged("errorRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface")]
    public partial class requestPensionsOpekaInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string amkaIdField;
        
        private string dateFromField;
        
        private string dateToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string amkaId {
            get {
                return this.amkaIdField;
            }
            set {
                this.amkaIdField = value;
                this.RaisePropertyChanged("amkaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dateFrom {
            get {
                return this.dateFromField;
            }
            set {
                this.dateFromField = value;
                this.RaisePropertyChanged("dateFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dateTo {
            get {
                return this.dateToField;
            }
            set {
                this.dateToField = value;
                this.RaisePropertyChanged("dateTo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface")]
    public partial class requestPensionsOpekaRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditRecord auditRecordField;
        
        private requestPensionsOpekaInput requestPensionsOpekaInputRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auditRecord auditRecord {
            get {
                return this.auditRecordField;
            }
            set {
                this.auditRecordField = value;
                this.RaisePropertyChanged("auditRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public requestPensionsOpekaInput requestPensionsOpekaInputRecord {
            get {
                return this.requestPensionsOpekaInputRecordField;
            }
            set {
                this.requestPensionsOpekaInputRecordField = value;
                this.RaisePropertyChanged("requestPensionsOpekaInputRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface")]
    public partial class salaryRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fMonthField;
        
        private string fSalaryField;
        
        private string fYearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fMonth {
            get {
                return this.fMonthField;
            }
            set {
                this.fMonthField = value;
                this.RaisePropertyChanged("fMonth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fSalary {
            get {
                return this.fSalaryField;
            }
            set {
                this.fSalaryField = value;
                this.RaisePropertyChanged("fSalary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fYear {
            get {
                return this.fYearField;
            }
            set {
                this.fYearField = value;
                this.RaisePropertyChanged("fYear");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface")]
    public partial class getSalaryEmpInfoReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string afmCheckField;
        
        private string amkaAfmCheckField;
        
        private string amkaCheckField;
        
        private salaryRecord[] salariesField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string afmCheck {
            get {
                return this.afmCheckField;
            }
            set {
                this.afmCheckField = value;
                this.RaisePropertyChanged("afmCheck");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string amkaAfmCheck {
            get {
                return this.amkaAfmCheckField;
            }
            set {
                this.amkaAfmCheckField = value;
                this.RaisePropertyChanged("amkaAfmCheck");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string amkaCheck {
            get {
                return this.amkaCheckField;
            }
            set {
                this.amkaCheckField = value;
                this.RaisePropertyChanged("amkaCheck");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public salaryRecord[] salaries {
            get {
                return this.salariesField;
            }
            set {
                this.salariesField = value;
                this.RaisePropertyChanged("salaries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
                this.RaisePropertyChanged("successSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface")]
    public partial class getSalaryEmpInfoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private getSalaryEmpInfoReturn getSalaryEmpInfoOutputRecordField;
        
        private decimal callSequenceIdField;
        
        private bool callSequenceIdFieldSpecified;
        
        private System.DateTime callSequenceDateField;
        
        private bool callSequenceDateFieldSpecified;
        
        private errorRecord errorRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public getSalaryEmpInfoReturn getSalaryEmpInfoOutputRecord {
            get {
                return this.getSalaryEmpInfoOutputRecordField;
            }
            set {
                this.getSalaryEmpInfoOutputRecordField = value;
                this.RaisePropertyChanged("getSalaryEmpInfoOutputRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal callSequenceId {
            get {
                return this.callSequenceIdField;
            }
            set {
                this.callSequenceIdField = value;
                this.RaisePropertyChanged("callSequenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool callSequenceIdSpecified {
            get {
                return this.callSequenceIdFieldSpecified;
            }
            set {
                this.callSequenceIdFieldSpecified = value;
                this.RaisePropertyChanged("callSequenceIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime callSequenceDate {
            get {
                return this.callSequenceDateField;
            }
            set {
                this.callSequenceDateField = value;
                this.RaisePropertyChanged("callSequenceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool callSequenceDateSpecified {
            get {
                return this.callSequenceDateFieldSpecified;
            }
            set {
                this.callSequenceDateFieldSpecified = value;
                this.RaisePropertyChanged("callSequenceDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public errorRecord errorRecord {
            get {
                return this.errorRecordField;
            }
            set {
                this.errorRecordField = value;
                this.RaisePropertyChanged("errorRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface")]
    public partial class getSalaryEmpInfoInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string amkaField;
        
        private string afmField;
        
        private decimal monthFromField;
        
        private bool monthFromFieldSpecified;
        
        private decimal yearFromField;
        
        private bool yearFromFieldSpecified;
        
        private decimal monthToField;
        
        private bool monthToFieldSpecified;
        
        private decimal yearToField;
        
        private bool yearToFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string amka {
            get {
                return this.amkaField;
            }
            set {
                this.amkaField = value;
                this.RaisePropertyChanged("amka");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string afm {
            get {
                return this.afmField;
            }
            set {
                this.afmField = value;
                this.RaisePropertyChanged("afm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal monthFrom {
            get {
                return this.monthFromField;
            }
            set {
                this.monthFromField = value;
                this.RaisePropertyChanged("monthFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool monthFromSpecified {
            get {
                return this.monthFromFieldSpecified;
            }
            set {
                this.monthFromFieldSpecified = value;
                this.RaisePropertyChanged("monthFromSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal yearFrom {
            get {
                return this.yearFromField;
            }
            set {
                this.yearFromField = value;
                this.RaisePropertyChanged("yearFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearFromSpecified {
            get {
                return this.yearFromFieldSpecified;
            }
            set {
                this.yearFromFieldSpecified = value;
                this.RaisePropertyChanged("yearFromSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal monthTo {
            get {
                return this.monthToField;
            }
            set {
                this.monthToField = value;
                this.RaisePropertyChanged("monthTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool monthToSpecified {
            get {
                return this.monthToFieldSpecified;
            }
            set {
                this.monthToFieldSpecified = value;
                this.RaisePropertyChanged("monthToSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal yearTo {
            get {
                return this.yearToField;
            }
            set {
                this.yearToField = value;
                this.RaisePropertyChanged("yearTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearToSpecified {
            get {
                return this.yearToFieldSpecified;
            }
            set {
                this.yearToFieldSpecified = value;
                this.RaisePropertyChanged("yearToSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSalaryEmpInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfoRequest getSalaryEmpInfoRequest;
        
        public getSalaryEmpInfo() {
        }
        
        public getSalaryEmpInfo(XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfoRequest getSalaryEmpInfoRequest) {
            this.getSalaryEmpInfoRequest = getSalaryEmpInfoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSalaryEmpInfoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfoResponse getSalaryEmpInfoResponse;
        
        public getSalaryEmpInfoResponse1() {
        }
        
        public getSalaryEmpInfoResponse1(XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfoResponse getSalaryEmpInfoResponse) {
            this.getSalaryEmpInfoResponse = getSalaryEmpInfoResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class requestPensionsOpeka {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpekaRequest requestPensionsOpekaRequest;
        
        public requestPensionsOpeka() {
        }
        
        public requestPensionsOpeka(XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpekaRequest requestPensionsOpekaRequest) {
            this.requestPensionsOpekaRequest = requestPensionsOpekaRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class requestPensionsOpekaResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpekaResponse requestPensionsOpekaResponse;
        
        public requestPensionsOpekaResponse1() {
        }
        
        public requestPensionsOpekaResponse1(XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpekaResponse requestPensionsOpekaResponse) {
            this.requestPensionsOpekaResponse = requestPensionsOpekaResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSalaryPensEmpInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfoRequest getSalaryPensEmpInfoRequest;
        
        public getSalaryPensEmpInfo() {
        }
        
        public getSalaryPensEmpInfo(XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfoRequest getSalaryPensEmpInfoRequest) {
            this.getSalaryPensEmpInfoRequest = getSalaryPensEmpInfoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSalaryPensEmpInfoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gsis.ggps.interoperability/salaryEmpInfoInterface", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfoResponse getSalaryPensEmpInfoResponse;
        
        public getSalaryPensEmpInfoResponse1() {
        }
        
        public getSalaryPensEmpInfoResponse1(XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfoResponse getSalaryPensEmpInfoResponse) {
            this.getSalaryPensEmpInfoResponse = getSalaryPensEmpInfoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface salaryEmpInfoInterfaceChannel : XServices.Efka.SalaryEmpInfoServiceReference.salaryEmpInfoInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class salaryEmpInfoInterfaceClient : System.ServiceModel.ClientBase<XServices.Efka.SalaryEmpInfoServiceReference.salaryEmpInfoInterface>, XServices.Efka.SalaryEmpInfoServiceReference.salaryEmpInfoInterface {
        
        public salaryEmpInfoInterfaceClient() {
        }
        
        public salaryEmpInfoInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public salaryEmpInfoInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public salaryEmpInfoInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public salaryEmpInfoInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfoResponse1 XServices.Efka.SalaryEmpInfoServiceReference.salaryEmpInfoInterface.getSalaryEmpInfo(XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfo request) {
            return base.Channel.getSalaryEmpInfo(request);
        }
        
        public XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfoResponse getSalaryEmpInfo(XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfoRequest getSalaryEmpInfoRequest) {
            XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfo inValue = new XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfo();
            inValue.getSalaryEmpInfoRequest = getSalaryEmpInfoRequest;
            XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfoResponse1 retVal = ((XServices.Efka.SalaryEmpInfoServiceReference.salaryEmpInfoInterface)(this)).getSalaryEmpInfo(inValue);
            return retVal.getSalaryEmpInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfoResponse1> XServices.Efka.SalaryEmpInfoServiceReference.salaryEmpInfoInterface.getSalaryEmpInfoAsync(XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfo request) {
            return base.Channel.getSalaryEmpInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfoResponse1> getSalaryEmpInfoAsync(XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfoRequest getSalaryEmpInfoRequest) {
            XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfo inValue = new XServices.Efka.SalaryEmpInfoServiceReference.getSalaryEmpInfo();
            inValue.getSalaryEmpInfoRequest = getSalaryEmpInfoRequest;
            return ((XServices.Efka.SalaryEmpInfoServiceReference.salaryEmpInfoInterface)(this)).getSalaryEmpInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpekaResponse1 XServices.Efka.SalaryEmpInfoServiceReference.salaryEmpInfoInterface.requestPensionsOpeka(XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpeka request) {
            return base.Channel.requestPensionsOpeka(request);
        }
        
        public XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpekaResponse requestPensionsOpeka(XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpekaRequest requestPensionsOpekaRequest) {
            XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpeka inValue = new XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpeka();
            inValue.requestPensionsOpekaRequest = requestPensionsOpekaRequest;
            XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpekaResponse1 retVal = ((XServices.Efka.SalaryEmpInfoServiceReference.salaryEmpInfoInterface)(this)).requestPensionsOpeka(inValue);
            return retVal.requestPensionsOpekaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpekaResponse1> XServices.Efka.SalaryEmpInfoServiceReference.salaryEmpInfoInterface.requestPensionsOpekaAsync(XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpeka request) {
            return base.Channel.requestPensionsOpekaAsync(request);
        }
        
        public System.Threading.Tasks.Task<XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpekaResponse1> requestPensionsOpekaAsync(XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpekaRequest requestPensionsOpekaRequest) {
            XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpeka inValue = new XServices.Efka.SalaryEmpInfoServiceReference.requestPensionsOpeka();
            inValue.requestPensionsOpekaRequest = requestPensionsOpekaRequest;
            return ((XServices.Efka.SalaryEmpInfoServiceReference.salaryEmpInfoInterface)(this)).requestPensionsOpekaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfoResponse1 XServices.Efka.SalaryEmpInfoServiceReference.salaryEmpInfoInterface.getSalaryPensEmpInfo(XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfo request) {
            return base.Channel.getSalaryPensEmpInfo(request);
        }
        
        public XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfoResponse getSalaryPensEmpInfo(XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfoRequest getSalaryPensEmpInfoRequest) {
            XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfo inValue = new XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfo();
            inValue.getSalaryPensEmpInfoRequest = getSalaryPensEmpInfoRequest;
            XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfoResponse1 retVal = ((XServices.Efka.SalaryEmpInfoServiceReference.salaryEmpInfoInterface)(this)).getSalaryPensEmpInfo(inValue);
            return retVal.getSalaryPensEmpInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfoResponse1> XServices.Efka.SalaryEmpInfoServiceReference.salaryEmpInfoInterface.getSalaryPensEmpInfoAsync(XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfo request) {
            return base.Channel.getSalaryPensEmpInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfoResponse1> getSalaryPensEmpInfoAsync(XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfoRequest getSalaryPensEmpInfoRequest) {
            XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfo inValue = new XServices.Efka.SalaryEmpInfoServiceReference.getSalaryPensEmpInfo();
            inValue.getSalaryPensEmpInfoRequest = getSalaryPensEmpInfoRequest;
            return ((XServices.Efka.SalaryEmpInfoServiceReference.salaryEmpInfoInterface)(this)).getSalaryPensEmpInfoAsync(inValue);
        }
    }
}
