//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XServices.Gsis.PropertyValueInfoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gsis.ggps.interoperability/propertyValueInfoInterface", ConfigurationName="PropertyValueInfoServiceReference.propertyValueInfoInterface")]
    public interface propertyValueInfoInterface {
        
        // CODEGEN: Generating message contract since the operation getPropertyValueE9 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getPropertyValueE9", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9Response1 getPropertyValueE9(XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getPropertyValueE9", ReplyAction="*")]
        System.Threading.Tasks.Task<XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9Response1> getPropertyValueE9Async(XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/propertyValueInfoInterface")]
    public partial class getPropertyValueE9Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditRecord auditRecordField;
        
        private getPropertyValueE9Input getPropertyValueE9InputRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auditRecord auditRecord {
            get {
                return this.auditRecordField;
            }
            set {
                this.auditRecordField = value;
                this.RaisePropertyChanged("auditRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public getPropertyValueE9Input getPropertyValueE9InputRecord {
            get {
                return this.getPropertyValueE9InputRecordField;
            }
            set {
                this.getPropertyValueE9InputRecordField = value;
                this.RaisePropertyChanged("getPropertyValueE9InputRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/propertyValueInfoInterface")]
    public partial class auditRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string auditTransactionIdField;
        
        private System.DateTime auditTransactionDateField;
        
        private string auditUnitField;
        
        private string auditProtocolField;
        
        private string auditUserIdField;
        
        private string auditUserIpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string auditTransactionId {
            get {
                return this.auditTransactionIdField;
            }
            set {
                this.auditTransactionIdField = value;
                this.RaisePropertyChanged("auditTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime auditTransactionDate {
            get {
                return this.auditTransactionDateField;
            }
            set {
                this.auditTransactionDateField = value;
                this.RaisePropertyChanged("auditTransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string auditUnit {
            get {
                return this.auditUnitField;
            }
            set {
                this.auditUnitField = value;
                this.RaisePropertyChanged("auditUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string auditProtocol {
            get {
                return this.auditProtocolField;
            }
            set {
                this.auditProtocolField = value;
                this.RaisePropertyChanged("auditProtocol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string auditUserId {
            get {
                return this.auditUserIdField;
            }
            set {
                this.auditUserIdField = value;
                this.RaisePropertyChanged("auditUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string auditUserIp {
            get {
                return this.auditUserIpField;
            }
            set {
                this.auditUserIpField = value;
                this.RaisePropertyChanged("auditUserIp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/propertyValueInfoInterface")]
    public partial class errorRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorDescrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorDescr {
            get {
                return this.errorDescrField;
            }
            set {
                this.errorDescrField = value;
                this.RaisePropertyChanged("errorDescr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/propertyValueInfoInterface")]
    public partial class getPropertyValueE9Return : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal axiaEnfiaField;
        
        private bool axiaEnfiaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal axiaEnfia {
            get {
                return this.axiaEnfiaField;
            }
            set {
                this.axiaEnfiaField = value;
                this.RaisePropertyChanged("axiaEnfia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool axiaEnfiaSpecified {
            get {
                return this.axiaEnfiaFieldSpecified;
            }
            set {
                this.axiaEnfiaFieldSpecified = value;
                this.RaisePropertyChanged("axiaEnfiaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/propertyValueInfoInterface")]
    public partial class getPropertyValueE9Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private getPropertyValueE9Return getPropertyValueE9OutputRecordField;
        
        private decimal callSequenceIdField;
        
        private bool callSequenceIdFieldSpecified;
        
        private System.DateTime callSequenceDateField;
        
        private bool callSequenceDateFieldSpecified;
        
        private errorRecord errorRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public getPropertyValueE9Return getPropertyValueE9OutputRecord {
            get {
                return this.getPropertyValueE9OutputRecordField;
            }
            set {
                this.getPropertyValueE9OutputRecordField = value;
                this.RaisePropertyChanged("getPropertyValueE9OutputRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal callSequenceId {
            get {
                return this.callSequenceIdField;
            }
            set {
                this.callSequenceIdField = value;
                this.RaisePropertyChanged("callSequenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool callSequenceIdSpecified {
            get {
                return this.callSequenceIdFieldSpecified;
            }
            set {
                this.callSequenceIdFieldSpecified = value;
                this.RaisePropertyChanged("callSequenceIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime callSequenceDate {
            get {
                return this.callSequenceDateField;
            }
            set {
                this.callSequenceDateField = value;
                this.RaisePropertyChanged("callSequenceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool callSequenceDateSpecified {
            get {
                return this.callSequenceDateFieldSpecified;
            }
            set {
                this.callSequenceDateFieldSpecified = value;
                this.RaisePropertyChanged("callSequenceDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public errorRecord errorRecord {
            get {
                return this.errorRecordField;
            }
            set {
                this.errorRecordField = value;
                this.RaisePropertyChanged("errorRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsis.ggps.interoperability/propertyValueInfoInterface")]
    public partial class getPropertyValueE9Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string afmField;
        
        private int etosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string afm {
            get {
                return this.afmField;
            }
            set {
                this.afmField = value;
                this.RaisePropertyChanged("afm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int etos {
            get {
                return this.etosField;
            }
            set {
                this.etosField = value;
                this.RaisePropertyChanged("etos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPropertyValueE9 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gsis.ggps.interoperability/propertyValueInfoInterface", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9Request getPropertyValueE9Request;
        
        public getPropertyValueE9() {
        }
        
        public getPropertyValueE9(XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9Request getPropertyValueE9Request) {
            this.getPropertyValueE9Request = getPropertyValueE9Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPropertyValueE9Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gsis.ggps.interoperability/propertyValueInfoInterface", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9Response getPropertyValueE9Response;
        
        public getPropertyValueE9Response1() {
        }
        
        public getPropertyValueE9Response1(XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9Response getPropertyValueE9Response) {
            this.getPropertyValueE9Response = getPropertyValueE9Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface propertyValueInfoInterfaceChannel : XServices.Gsis.PropertyValueInfoServiceReference.propertyValueInfoInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class propertyValueInfoInterfaceClient : System.ServiceModel.ClientBase<XServices.Gsis.PropertyValueInfoServiceReference.propertyValueInfoInterface>, XServices.Gsis.PropertyValueInfoServiceReference.propertyValueInfoInterface {
        
        public propertyValueInfoInterfaceClient() {
        }
        
        public propertyValueInfoInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public propertyValueInfoInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public propertyValueInfoInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public propertyValueInfoInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9Response1 XServices.Gsis.PropertyValueInfoServiceReference.propertyValueInfoInterface.getPropertyValueE9(XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9 request) {
            return base.Channel.getPropertyValueE9(request);
        }
        
        public XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9Response getPropertyValueE9(XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9Request getPropertyValueE9Request) {
            XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9 inValue = new XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9();
            inValue.getPropertyValueE9Request = getPropertyValueE9Request;
            XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9Response1 retVal = ((XServices.Gsis.PropertyValueInfoServiceReference.propertyValueInfoInterface)(this)).getPropertyValueE9(inValue);
            return retVal.getPropertyValueE9Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9Response1> XServices.Gsis.PropertyValueInfoServiceReference.propertyValueInfoInterface.getPropertyValueE9Async(XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9 request) {
            return base.Channel.getPropertyValueE9Async(request);
        }
        
        public System.Threading.Tasks.Task<XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9Response1> getPropertyValueE9Async(XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9Request getPropertyValueE9Request) {
            XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9 inValue = new XServices.Gsis.PropertyValueInfoServiceReference.getPropertyValueE9();
            inValue.getPropertyValueE9Request = getPropertyValueE9Request;
            return ((XServices.Gsis.PropertyValueInfoServiceReference.propertyValueInfoInterface)(this)).getPropertyValueE9Async(inValue);
        }
    }
}
