//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XService.Idika.AMKA_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WS_Response", Namespace="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/")]
    [System.SerializableAttribute()]
    public partial class WS_Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STATUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MESSAGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AMKA_ServiceReference.Details> RECORDSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string STATUS {
            get {
                return this.STATUSField;
            }
            set {
                if ((object.ReferenceEquals(this.STATUSField, value) != true)) {
                    this.STATUSField = value;
                    this.RaisePropertyChanged("STATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MESSAGE {
            get {
                return this.MESSAGEField;
            }
            set {
                if ((object.ReferenceEquals(this.MESSAGEField, value) != true)) {
                    this.MESSAGEField = value;
                    this.RaisePropertyChanged("MESSAGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.Generic.List<AMKA_ServiceReference.Details> RECORDS {
            get {
                return this.RECORDSField;
            }
            set {
                if ((object.ReferenceEquals(this.RECORDSField, value) != true)) {
                    this.RECORDSField = value;
                    this.RaisePropertyChanged("RECORDS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Details", Namespace="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/")]
    [System.SerializableAttribute()]
    public partial class Details : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AMKA_ARXIKOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AMKA_ISXYWNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EPWN_GEN_GRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EPWN_GEN_LATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EPWN_TREX_GRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EPWN_TREX_LATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ONOM_GRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ONOM_LATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PATR_GRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PATR_LATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KWD_FYLOYField;
        
        private System.DateTime HMNIA_GENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XWRA_GR_GENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XWRA_GR_YPHKOOTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ARIQ_TAYTOTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KWD_EIDOYS_TAYTOTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KWD_PLASM_HMNIAS_GENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DHMOS_GENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KWD_NOMOY_GENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MHTR_GRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MHTR_LATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EPWN_SYZYGOY_GRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EPWN_SYZYGOY_LATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ONOM_SYZYGOY_GRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ONOM_SYZYGOY_LATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ODOS_ARIQ_DIEYQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TAXYKWDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DHMOS_DIEYQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KWD_NOMOY_DIEYQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XWRA_GR_DIEYQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string THLEF1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string THLEF2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AFMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string END_QANATOYField;
        
        private System.DateTime HMNIA_QANATOYField;
        
        private int ETOS_EKDOSHS_TAYTOTField;
        
        private System.DateTime HMNIA_KATAXWRField;
        
        private System.DateTime HMNIA_METABField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AMKA_ARXIKOS {
            get {
                return this.AMKA_ARXIKOSField;
            }
            set {
                if ((object.ReferenceEquals(this.AMKA_ARXIKOSField, value) != true)) {
                    this.AMKA_ARXIKOSField = value;
                    this.RaisePropertyChanged("AMKA_ARXIKOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AMKA_ISXYWN {
            get {
                return this.AMKA_ISXYWNField;
            }
            set {
                if ((object.ReferenceEquals(this.AMKA_ISXYWNField, value) != true)) {
                    this.AMKA_ISXYWNField = value;
                    this.RaisePropertyChanged("AMKA_ISXYWN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EPWN_GEN_GR {
            get {
                return this.EPWN_GEN_GRField;
            }
            set {
                if ((object.ReferenceEquals(this.EPWN_GEN_GRField, value) != true)) {
                    this.EPWN_GEN_GRField = value;
                    this.RaisePropertyChanged("EPWN_GEN_GR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EPWN_GEN_LAT {
            get {
                return this.EPWN_GEN_LATField;
            }
            set {
                if ((object.ReferenceEquals(this.EPWN_GEN_LATField, value) != true)) {
                    this.EPWN_GEN_LATField = value;
                    this.RaisePropertyChanged("EPWN_GEN_LAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EPWN_TREX_GR {
            get {
                return this.EPWN_TREX_GRField;
            }
            set {
                if ((object.ReferenceEquals(this.EPWN_TREX_GRField, value) != true)) {
                    this.EPWN_TREX_GRField = value;
                    this.RaisePropertyChanged("EPWN_TREX_GR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EPWN_TREX_LAT {
            get {
                return this.EPWN_TREX_LATField;
            }
            set {
                if ((object.ReferenceEquals(this.EPWN_TREX_LATField, value) != true)) {
                    this.EPWN_TREX_LATField = value;
                    this.RaisePropertyChanged("EPWN_TREX_LAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ONOM_GR {
            get {
                return this.ONOM_GRField;
            }
            set {
                if ((object.ReferenceEquals(this.ONOM_GRField, value) != true)) {
                    this.ONOM_GRField = value;
                    this.RaisePropertyChanged("ONOM_GR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ONOM_LAT {
            get {
                return this.ONOM_LATField;
            }
            set {
                if ((object.ReferenceEquals(this.ONOM_LATField, value) != true)) {
                    this.ONOM_LATField = value;
                    this.RaisePropertyChanged("ONOM_LAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PATR_GR {
            get {
                return this.PATR_GRField;
            }
            set {
                if ((object.ReferenceEquals(this.PATR_GRField, value) != true)) {
                    this.PATR_GRField = value;
                    this.RaisePropertyChanged("PATR_GR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PATR_LAT {
            get {
                return this.PATR_LATField;
            }
            set {
                if ((object.ReferenceEquals(this.PATR_LATField, value) != true)) {
                    this.PATR_LATField = value;
                    this.RaisePropertyChanged("PATR_LAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string KWD_FYLOY {
            get {
                return this.KWD_FYLOYField;
            }
            set {
                if ((object.ReferenceEquals(this.KWD_FYLOYField, value) != true)) {
                    this.KWD_FYLOYField = value;
                    this.RaisePropertyChanged("KWD_FYLOY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime HMNIA_GEN {
            get {
                return this.HMNIA_GENField;
            }
            set {
                if ((this.HMNIA_GENField.Equals(value) != true)) {
                    this.HMNIA_GENField = value;
                    this.RaisePropertyChanged("HMNIA_GEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string XWRA_GR_GEN {
            get {
                return this.XWRA_GR_GENField;
            }
            set {
                if ((object.ReferenceEquals(this.XWRA_GR_GENField, value) != true)) {
                    this.XWRA_GR_GENField = value;
                    this.RaisePropertyChanged("XWRA_GR_GEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string XWRA_GR_YPHKOOT {
            get {
                return this.XWRA_GR_YPHKOOTField;
            }
            set {
                if ((object.ReferenceEquals(this.XWRA_GR_YPHKOOTField, value) != true)) {
                    this.XWRA_GR_YPHKOOTField = value;
                    this.RaisePropertyChanged("XWRA_GR_YPHKOOT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string ARIQ_TAYTOT {
            get {
                return this.ARIQ_TAYTOTField;
            }
            set {
                if ((object.ReferenceEquals(this.ARIQ_TAYTOTField, value) != true)) {
                    this.ARIQ_TAYTOTField = value;
                    this.RaisePropertyChanged("ARIQ_TAYTOT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string KWD_EIDOYS_TAYTOT {
            get {
                return this.KWD_EIDOYS_TAYTOTField;
            }
            set {
                if ((object.ReferenceEquals(this.KWD_EIDOYS_TAYTOTField, value) != true)) {
                    this.KWD_EIDOYS_TAYTOTField = value;
                    this.RaisePropertyChanged("KWD_EIDOYS_TAYTOT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string KWD_PLASM_HMNIAS_GEN {
            get {
                return this.KWD_PLASM_HMNIAS_GENField;
            }
            set {
                if ((object.ReferenceEquals(this.KWD_PLASM_HMNIAS_GENField, value) != true)) {
                    this.KWD_PLASM_HMNIAS_GENField = value;
                    this.RaisePropertyChanged("KWD_PLASM_HMNIAS_GEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string DHMOS_GEN {
            get {
                return this.DHMOS_GENField;
            }
            set {
                if ((object.ReferenceEquals(this.DHMOS_GENField, value) != true)) {
                    this.DHMOS_GENField = value;
                    this.RaisePropertyChanged("DHMOS_GEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string KWD_NOMOY_GEN {
            get {
                return this.KWD_NOMOY_GENField;
            }
            set {
                if ((object.ReferenceEquals(this.KWD_NOMOY_GENField, value) != true)) {
                    this.KWD_NOMOY_GENField = value;
                    this.RaisePropertyChanged("KWD_NOMOY_GEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string MHTR_GR {
            get {
                return this.MHTR_GRField;
            }
            set {
                if ((object.ReferenceEquals(this.MHTR_GRField, value) != true)) {
                    this.MHTR_GRField = value;
                    this.RaisePropertyChanged("MHTR_GR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string MHTR_LAT {
            get {
                return this.MHTR_LATField;
            }
            set {
                if ((object.ReferenceEquals(this.MHTR_LATField, value) != true)) {
                    this.MHTR_LATField = value;
                    this.RaisePropertyChanged("MHTR_LAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string EPWN_SYZYGOY_GR {
            get {
                return this.EPWN_SYZYGOY_GRField;
            }
            set {
                if ((object.ReferenceEquals(this.EPWN_SYZYGOY_GRField, value) != true)) {
                    this.EPWN_SYZYGOY_GRField = value;
                    this.RaisePropertyChanged("EPWN_SYZYGOY_GR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string EPWN_SYZYGOY_LAT {
            get {
                return this.EPWN_SYZYGOY_LATField;
            }
            set {
                if ((object.ReferenceEquals(this.EPWN_SYZYGOY_LATField, value) != true)) {
                    this.EPWN_SYZYGOY_LATField = value;
                    this.RaisePropertyChanged("EPWN_SYZYGOY_LAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string ONOM_SYZYGOY_GR {
            get {
                return this.ONOM_SYZYGOY_GRField;
            }
            set {
                if ((object.ReferenceEquals(this.ONOM_SYZYGOY_GRField, value) != true)) {
                    this.ONOM_SYZYGOY_GRField = value;
                    this.RaisePropertyChanged("ONOM_SYZYGOY_GR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string ONOM_SYZYGOY_LAT {
            get {
                return this.ONOM_SYZYGOY_LATField;
            }
            set {
                if ((object.ReferenceEquals(this.ONOM_SYZYGOY_LATField, value) != true)) {
                    this.ONOM_SYZYGOY_LATField = value;
                    this.RaisePropertyChanged("ONOM_SYZYGOY_LAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string ODOS_ARIQ_DIEYQ {
            get {
                return this.ODOS_ARIQ_DIEYQField;
            }
            set {
                if ((object.ReferenceEquals(this.ODOS_ARIQ_DIEYQField, value) != true)) {
                    this.ODOS_ARIQ_DIEYQField = value;
                    this.RaisePropertyChanged("ODOS_ARIQ_DIEYQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string TAXYKWD {
            get {
                return this.TAXYKWDField;
            }
            set {
                if ((object.ReferenceEquals(this.TAXYKWDField, value) != true)) {
                    this.TAXYKWDField = value;
                    this.RaisePropertyChanged("TAXYKWD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string DHMOS_DIEYQ {
            get {
                return this.DHMOS_DIEYQField;
            }
            set {
                if ((object.ReferenceEquals(this.DHMOS_DIEYQField, value) != true)) {
                    this.DHMOS_DIEYQField = value;
                    this.RaisePropertyChanged("DHMOS_DIEYQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string KWD_NOMOY_DIEYQ {
            get {
                return this.KWD_NOMOY_DIEYQField;
            }
            set {
                if ((object.ReferenceEquals(this.KWD_NOMOY_DIEYQField, value) != true)) {
                    this.KWD_NOMOY_DIEYQField = value;
                    this.RaisePropertyChanged("KWD_NOMOY_DIEYQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string XWRA_GR_DIEYQ {
            get {
                return this.XWRA_GR_DIEYQField;
            }
            set {
                if ((object.ReferenceEquals(this.XWRA_GR_DIEYQField, value) != true)) {
                    this.XWRA_GR_DIEYQField = value;
                    this.RaisePropertyChanged("XWRA_GR_DIEYQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string THLEF1 {
            get {
                return this.THLEF1Field;
            }
            set {
                if ((object.ReferenceEquals(this.THLEF1Field, value) != true)) {
                    this.THLEF1Field = value;
                    this.RaisePropertyChanged("THLEF1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string THLEF2 {
            get {
                return this.THLEF2Field;
            }
            set {
                if ((object.ReferenceEquals(this.THLEF2Field, value) != true)) {
                    this.THLEF2Field = value;
                    this.RaisePropertyChanged("THLEF2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string AFM {
            get {
                return this.AFMField;
            }
            set {
                if ((object.ReferenceEquals(this.AFMField, value) != true)) {
                    this.AFMField = value;
                    this.RaisePropertyChanged("AFM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string END_QANATOY {
            get {
                return this.END_QANATOYField;
            }
            set {
                if ((object.ReferenceEquals(this.END_QANATOYField, value) != true)) {
                    this.END_QANATOYField = value;
                    this.RaisePropertyChanged("END_QANATOY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=34)]
        public System.DateTime HMNIA_QANATOY {
            get {
                return this.HMNIA_QANATOYField;
            }
            set {
                if ((this.HMNIA_QANATOYField.Equals(value) != true)) {
                    this.HMNIA_QANATOYField = value;
                    this.RaisePropertyChanged("HMNIA_QANATOY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=35)]
        public int ETOS_EKDOSHS_TAYTOT {
            get {
                return this.ETOS_EKDOSHS_TAYTOTField;
            }
            set {
                if ((this.ETOS_EKDOSHS_TAYTOTField.Equals(value) != true)) {
                    this.ETOS_EKDOSHS_TAYTOTField = value;
                    this.RaisePropertyChanged("ETOS_EKDOSHS_TAYTOT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=36)]
        public System.DateTime HMNIA_KATAXWR {
            get {
                return this.HMNIA_KATAXWRField;
            }
            set {
                if ((this.HMNIA_KATAXWRField.Equals(value) != true)) {
                    this.HMNIA_KATAXWRField = value;
                    this.RaisePropertyChanged("HMNIA_KATAXWR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=37)]
        public System.DateTime HMNIA_METAB {
            get {
                return this.HMNIA_METABField;
            }
            set {
                if ((this.HMNIA_METABField.Equals(value) != true)) {
                    this.HMNIA_METABField = value;
                    this.RaisePropertyChanged("HMNIA_METAB");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WS_Melh_Response", Namespace="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/")]
    [System.SerializableAttribute()]
    public partial class WS_Melh_Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STATUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MESSAGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AMKA_ServiceReference.Melh_Details> RECORDSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string STATUS {
            get {
                return this.STATUSField;
            }
            set {
                if ((object.ReferenceEquals(this.STATUSField, value) != true)) {
                    this.STATUSField = value;
                    this.RaisePropertyChanged("STATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MESSAGE {
            get {
                return this.MESSAGEField;
            }
            set {
                if ((object.ReferenceEquals(this.MESSAGEField, value) != true)) {
                    this.MESSAGEField = value;
                    this.RaisePropertyChanged("MESSAGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.Generic.List<AMKA_ServiceReference.Melh_Details> RECORDS {
            get {
                return this.RECORDSField;
            }
            set {
                if ((object.ReferenceEquals(this.RECORDSField, value) != true)) {
                    this.RECORDSField = value;
                    this.RaisePropertyChanged("RECORDS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Melh_Details", Namespace="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/")]
    [System.SerializableAttribute()]
    public partial class Melh_Details : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PARENT_AMKAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MEMBER_AMKAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MEMBER_TYPEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PARENT_AMKA {
            get {
                return this.PARENT_AMKAField;
            }
            set {
                if ((object.ReferenceEquals(this.PARENT_AMKAField, value) != true)) {
                    this.PARENT_AMKAField = value;
                    this.RaisePropertyChanged("PARENT_AMKA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MEMBER_AMKA {
            get {
                return this.MEMBER_AMKAField;
            }
            set {
                if ((object.ReferenceEquals(this.MEMBER_AMKAField, value) != true)) {
                    this.MEMBER_AMKAField = value;
                    this.RaisePropertyChanged("MEMBER_AMKA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MEMBER_TYPE {
            get {
                return this.MEMBER_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.MEMBER_TYPEField, value) != true)) {
                    this.MEMBER_TYPEField = value;
                    this.RaisePropertyChanged("MEMBER_TYPE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/", ConfigurationName="AMKA_ServiceReference.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name user_ed from namespace https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/AFM2D", ReplyAction="*")]
        AMKA_ServiceReference.AFM2DResponse AFM2D(AMKA_ServiceReference.AFM2DRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/AFM2D", ReplyAction="*")]
        System.Threading.Tasks.Task<AMKA_ServiceReference.AFM2DResponse> AFM2DAsync(AMKA_ServiceReference.AFM2DRequest request);
        
        // CODEGEN: Generating message contract since element name user_ed from namespace https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/EMMESA_MELH", ReplyAction="*")]
        AMKA_ServiceReference.EMMESA_MELHResponse EMMESA_MELH(AMKA_ServiceReference.EMMESA_MELHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/EMMESA_MELH", ReplyAction="*")]
        System.Threading.Tasks.Task<AMKA_ServiceReference.EMMESA_MELHResponse> EMMESA_MELHAsync(AMKA_ServiceReference.EMMESA_MELHRequest request);
        
        // CODEGEN: Generating message contract since element name user_ed from namespace https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/FIND_AMESA", ReplyAction="*")]
        AMKA_ServiceReference.FIND_AMESAResponse FIND_AMESA(AMKA_ServiceReference.FIND_AMESARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/FIND_AMESA", ReplyAction="*")]
        System.Threading.Tasks.Task<AMKA_ServiceReference.FIND_AMESAResponse> FIND_AMESAAsync(AMKA_ServiceReference.FIND_AMESARequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AFM2DRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AFM2D", Namespace="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/", Order=0)]
        public AMKA_ServiceReference.AFM2DRequestBody Body;
        
        public AFM2DRequest() {
        }
        
        public AFM2DRequest(AMKA_ServiceReference.AFM2DRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/")]
    public partial class AFM2DRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user_ed;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password_ed;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string amka;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string afm;
        
        public AFM2DRequestBody() {
        }
        
        public AFM2DRequestBody(string user_ed, string password_ed, string amka, string afm) {
            this.user_ed = user_ed;
            this.password_ed = password_ed;
            this.amka = amka;
            this.afm = afm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AFM2DResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AFM2DResponse", Namespace="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/", Order=0)]
        public AMKA_ServiceReference.AFM2DResponseBody Body;
        
        public AFM2DResponse() {
        }
        
        public AFM2DResponse(AMKA_ServiceReference.AFM2DResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/")]
    public partial class AFM2DResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AMKA_ServiceReference.WS_Response AFM2DResult;
        
        public AFM2DResponseBody() {
        }
        
        public AFM2DResponseBody(AMKA_ServiceReference.WS_Response AFM2DResult) {
            this.AFM2DResult = AFM2DResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EMMESA_MELHRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EMMESA_MELH", Namespace="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/", Order=0)]
        public AMKA_ServiceReference.EMMESA_MELHRequestBody Body;
        
        public EMMESA_MELHRequest() {
        }
        
        public EMMESA_MELHRequest(AMKA_ServiceReference.EMMESA_MELHRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/")]
    public partial class EMMESA_MELHRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user_ed;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password_ed;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string amka;
        
        public EMMESA_MELHRequestBody() {
        }
        
        public EMMESA_MELHRequestBody(string user_ed, string password_ed, string amka) {
            this.user_ed = user_ed;
            this.password_ed = password_ed;
            this.amka = amka;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EMMESA_MELHResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EMMESA_MELHResponse", Namespace="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/", Order=0)]
        public AMKA_ServiceReference.EMMESA_MELHResponseBody Body;
        
        public EMMESA_MELHResponse() {
        }
        
        public EMMESA_MELHResponse(AMKA_ServiceReference.EMMESA_MELHResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/")]
    public partial class EMMESA_MELHResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AMKA_ServiceReference.WS_Melh_Response EMMESA_MELHResult;
        
        public EMMESA_MELHResponseBody() {
        }
        
        public EMMESA_MELHResponseBody(AMKA_ServiceReference.WS_Melh_Response EMMESA_MELHResult) {
            this.EMMESA_MELHResult = EMMESA_MELHResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FIND_AMESARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FIND_AMESA", Namespace="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/", Order=0)]
        public AMKA_ServiceReference.FIND_AMESARequestBody Body;
        
        public FIND_AMESARequest() {
        }
        
        public FIND_AMESARequest(AMKA_ServiceReference.FIND_AMESARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/")]
    public partial class FIND_AMESARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user_ed;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password_ed;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string amka;
        
        public FIND_AMESARequestBody() {
        }
        
        public FIND_AMESARequestBody(string user_ed, string password_ed, string amka) {
            this.user_ed = user_ed;
            this.password_ed = password_ed;
            this.amka = amka;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FIND_AMESAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FIND_AMESAResponse", Namespace="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/", Order=0)]
        public AMKA_ServiceReference.FIND_AMESAResponseBody Body;
        
        public FIND_AMESAResponse() {
        }
        
        public FIND_AMESAResponse(AMKA_ServiceReference.FIND_AMESAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.idika.gov.gr/AMKAWEBSERVICES/AFM2DATA/")]
    public partial class FIND_AMESAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AMKA_ServiceReference.WS_Melh_Response FIND_AMESAResult;
        
        public FIND_AMESAResponseBody() {
        }
        
        public FIND_AMESAResponseBody(AMKA_ServiceReference.WS_Melh_Response FIND_AMESAResult) {
            this.FIND_AMESAResult = FIND_AMESAResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : AMKA_ServiceReference.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<AMKA_ServiceReference.ServiceSoap>, AMKA_ServiceReference.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AMKA_ServiceReference.AFM2DResponse AMKA_ServiceReference.ServiceSoap.AFM2D(AMKA_ServiceReference.AFM2DRequest request) {
            return base.Channel.AFM2D(request);
        }
        
        public AMKA_ServiceReference.WS_Response AFM2D(string user_ed, string password_ed, string amka, string afm) {
            AMKA_ServiceReference.AFM2DRequest inValue = new AMKA_ServiceReference.AFM2DRequest();
            inValue.Body = new AMKA_ServiceReference.AFM2DRequestBody();
            inValue.Body.user_ed = user_ed;
            inValue.Body.password_ed = password_ed;
            inValue.Body.amka = amka;
            inValue.Body.afm = afm;
            AMKA_ServiceReference.AFM2DResponse retVal = ((AMKA_ServiceReference.ServiceSoap)(this)).AFM2D(inValue);
            return retVal.Body.AFM2DResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AMKA_ServiceReference.AFM2DResponse> AMKA_ServiceReference.ServiceSoap.AFM2DAsync(AMKA_ServiceReference.AFM2DRequest request) {
            return base.Channel.AFM2DAsync(request);
        }
        
        public System.Threading.Tasks.Task<AMKA_ServiceReference.AFM2DResponse> AFM2DAsync(string user_ed, string password_ed, string amka, string afm) {
            AMKA_ServiceReference.AFM2DRequest inValue = new AMKA_ServiceReference.AFM2DRequest();
            inValue.Body = new AMKA_ServiceReference.AFM2DRequestBody();
            inValue.Body.user_ed = user_ed;
            inValue.Body.password_ed = password_ed;
            inValue.Body.amka = amka;
            inValue.Body.afm = afm;
            return ((AMKA_ServiceReference.ServiceSoap)(this)).AFM2DAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AMKA_ServiceReference.EMMESA_MELHResponse AMKA_ServiceReference.ServiceSoap.EMMESA_MELH(AMKA_ServiceReference.EMMESA_MELHRequest request) {
            return base.Channel.EMMESA_MELH(request);
        }
        
        public AMKA_ServiceReference.WS_Melh_Response EMMESA_MELH(string user_ed, string password_ed, string amka) {
            AMKA_ServiceReference.EMMESA_MELHRequest inValue = new AMKA_ServiceReference.EMMESA_MELHRequest();
            inValue.Body = new AMKA_ServiceReference.EMMESA_MELHRequestBody();
            inValue.Body.user_ed = user_ed;
            inValue.Body.password_ed = password_ed;
            inValue.Body.amka = amka;
            AMKA_ServiceReference.EMMESA_MELHResponse retVal = ((AMKA_ServiceReference.ServiceSoap)(this)).EMMESA_MELH(inValue);
            return retVal.Body.EMMESA_MELHResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AMKA_ServiceReference.EMMESA_MELHResponse> AMKA_ServiceReference.ServiceSoap.EMMESA_MELHAsync(AMKA_ServiceReference.EMMESA_MELHRequest request) {
            return base.Channel.EMMESA_MELHAsync(request);
        }
        
        public System.Threading.Tasks.Task<AMKA_ServiceReference.EMMESA_MELHResponse> EMMESA_MELHAsync(string user_ed, string password_ed, string amka) {
            AMKA_ServiceReference.EMMESA_MELHRequest inValue = new AMKA_ServiceReference.EMMESA_MELHRequest();
            inValue.Body = new AMKA_ServiceReference.EMMESA_MELHRequestBody();
            inValue.Body.user_ed = user_ed;
            inValue.Body.password_ed = password_ed;
            inValue.Body.amka = amka;
            return ((AMKA_ServiceReference.ServiceSoap)(this)).EMMESA_MELHAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AMKA_ServiceReference.FIND_AMESAResponse AMKA_ServiceReference.ServiceSoap.FIND_AMESA(AMKA_ServiceReference.FIND_AMESARequest request) {
            return base.Channel.FIND_AMESA(request);
        }
        
        public AMKA_ServiceReference.WS_Melh_Response FIND_AMESA(string user_ed, string password_ed, string amka) {
            AMKA_ServiceReference.FIND_AMESARequest inValue = new AMKA_ServiceReference.FIND_AMESARequest();
            inValue.Body = new AMKA_ServiceReference.FIND_AMESARequestBody();
            inValue.Body.user_ed = user_ed;
            inValue.Body.password_ed = password_ed;
            inValue.Body.amka = amka;
            AMKA_ServiceReference.FIND_AMESAResponse retVal = ((AMKA_ServiceReference.ServiceSoap)(this)).FIND_AMESA(inValue);
            return retVal.Body.FIND_AMESAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AMKA_ServiceReference.FIND_AMESAResponse> AMKA_ServiceReference.ServiceSoap.FIND_AMESAAsync(AMKA_ServiceReference.FIND_AMESARequest request) {
            return base.Channel.FIND_AMESAAsync(request);
        }
        
        public System.Threading.Tasks.Task<AMKA_ServiceReference.FIND_AMESAResponse> FIND_AMESAAsync(string user_ed, string password_ed, string amka) {
            AMKA_ServiceReference.FIND_AMESARequest inValue = new AMKA_ServiceReference.FIND_AMESARequest();
            inValue.Body = new AMKA_ServiceReference.FIND_AMESARequestBody();
            inValue.Body.user_ed = user_ed;
            inValue.Body.password_ed = password_ed;
            inValue.Body.amka = amka;
            return ((AMKA_ServiceReference.ServiceSoap)(this)).FIND_AMESAAsync(inValue);
        }
    }
}
